# Generated by Django 4.0.4 on 2022-04-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20220129_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveresult',
            name='output',
            field=models.TextField(),
        ),
    ]
