# Generated by Django 4.1.4 on 2022-12-07 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_archiveresult_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveresult',
            name='extractor',
            field=models.CharField(choices=[('favicon', 'favicon'), ('headers', 'headers'), ('singlefile', 'singlefile'), ('pdf', 'pdf'), ('screenshot', 'screenshot'), ('dom', 'dom'), ('wget', 'wget'), ('title', 'title'), ('readability', 'readability'), ('mercury', 'mercury'), ('keywords', 'keywords'), ('git', 'git'), ('media', 'media'), ('archive_org', 'archive_org')], max_length=32),
        ),
        migrations.CreateModel(
            name='SnapshotTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.snapshot')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='tags',
        ),
        migrations.AddField(
            model_name='snapshot',
            name='tags',
            field=models.ManyToManyField(blank=True, through='core.SnapshotTag', to='core.tag'),
        ),
    ]
